github: [metadata]

title: Escape Room Project
description: Algemene informatie i.v.m. het project

search_enabled: true
theme: jekyll-theme-cayman

search_tokenizer_separator: /[\s/]+/

markdown: kramdown