github: [metadata]

title: Escape Room Project
description: Algemene informatie i.v.m. het project

search_enabled: true

remote_theme: pmarsceill/just-the-docs
# theme: jekyll-theme-cayman

logo: "favicon.png"

search_tokenizer_separator: /[\s/]+/

markdown: kramdown

footer_content: "Written by Arne Reyniers and Robin Uyttendaele."